name: Check stylelint

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install stylelint stylelint-config-standard@7.0.0
      - run: |
          echo '{"extends": "stylelint-config-standard"}' >> .stylelintrc.json
      - run: |
          npx stylelint '**/*.{css,scss}' \
            | ruby -pe 'sub(/^(.+):(\d+):(\d+): (.+) \[(.+)\]$/, %q{::\5 file=\1,line=\2,col=\3::\4})'
        shell: bash